/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class application_Database */

#ifndef _Included_application_Database
#define _Included_application_Database
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     application_Database
 * Method:    createDatabase
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_application_Database_createDatabase
  (JNIEnv *, jobject, jstring);

/*
 * Class:     application_Database
 * Method:    openDatabase
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_application_Database_openDatabase
  (JNIEnv *, jobject, jstring);

/*
 * Class:     application_Database
 * Method:    saveDatabase
 * Signature: (Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_application_Database_saveDatabase
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     application_Database
 * Method:    executeQuery
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_application_Database_executeQuery
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     application_Database
 * Method:    getTablesNames
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_application_Database_getTablesNames
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
